from artiq.experiment import *
# TTL output test for channels 4 to 15
class TTL_Output_All(EnvExperiment):
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl4")
        self.setattr_device("ttl5")
        self.setattr_device("ttl6")
        self.setattr_device("ttl7")
        self.setattr_device("ttl8")
        self.setattr_device("ttl9")
        self.setattr_device("ttl10")
        self.setattr_device("ttl11")
        self.setattr_device("ttl12")
        self.setattr_device("ttl13")
        self.setattr_device("ttl14")
        self.setattr_device("ttl15")

    @kernel
    def run(self):
        self.core.reset()
        self.ttl4.output()
        self.ttl5.output()
        self.ttl6.output()
        self.ttl7.output()
        self.ttl8.output()
        self.ttl9.output()
        self.ttl10.output()
        self.ttl11.output()
        self.ttl12.output()
        self.ttl13.output()
        self.ttl14.output()
        self.ttl15.output()
        
        for j in range(40000):
            # All off
            with parallel:
                self.ttl4.off()
                self.ttl5.off()
                self.ttl6.off()
                self.ttl7.off()
                self.ttl8.off()
                self.ttl9.off()
                self.ttl10.off()
                self.ttl11.off()
                self.ttl12.off()
                self.ttl13.off()
                self.ttl14.off()
                self.ttl15.off()
                delay(50*ms)
            # All on
            with parallel:
                self.ttl4.on()
                self.ttl5.on()
                self.ttl6.on()
                self.ttl7.on()
                self.ttl8.on()
                self.ttl9.on()
                self.ttl10.on()
                self.ttl11.on()
                self.ttl12.on()
                self.ttl13.on()
                self.ttl14.on()
                self.ttl15.on()
                delay(50*ms)
            # Even on, odd off
            with parallel:
                self.ttl4.on()
                self.ttl5.off()
                self.ttl6.on()
                self.ttl7.off()
                self.ttl8.on()
                self.ttl9.off()
                self.ttl10.on()
                self.ttl11.off()
                self.ttl12.on()
                self.ttl13.off()
                self.ttl14.on()
                self.ttl15.off()
                delay(50*ms)
            # Odd on, even off
            with parallel:
                self.ttl4.off()
                self.ttl5.on()
                self.ttl6.off()
                self.ttl7.on()
                self.ttl8.off()
                self.ttl9.on()
                self.ttl10.off()
                self.ttl11.on()
                self.ttl12.off()
                self.ttl13.on()
                self.ttl14.off()
                self.ttl15.on()
                delay(50*ms)